// Mock Users Data
export const mockUsers = [
  {
    id: '1',
    initials: 'JM',
    name: 'John Mitchell',
    email: 'john.mitchell@email.com',
    status: 'active',
    role: 'VIP',
    balance: 12450,
    games: 342,
    winRate: 68,
    lastActive: '2 min ago',
  },
  {
    id: '2',
    initials: 'SC',
    name: 'Sarah Chen',
    email: 'sarah.chen@email.com',
    status: 'active',
    role: 'Premium',
    balance: 8200,
    games: 156,
    winRate: 72,
    lastActive: '15 min ago',
  },
  {
    id: '3',
    initials: 'MW',
    name: 'Marcus Williams',
    email: 'm.williams@email.com',
    status: 'inactive',
    role: 'Player',
    balance: 450,
    games: 89,
    winRate: 45,
    lastActive: '3 days ago',
  },
  {
    id: '4',
    initials: 'ER',
    name: 'Emily Rodriguez',
    email: 'emily.r@email.com',
    status: 'suspended',
    role: 'Player',
    balance: 0,
    games: 234,
    winRate: 38,
    lastActive: '1 week ago',
  },
  {
    id: '5',
    initials: 'DK',
    name: 'David Kim',
    email: 'david.kim@email.com',
    status: 'pending',
    role: 'Player',
    balance: 100,
    games: 0,
    winRate: 0,
    lastActive: 'Just now',
  },
  {
    id: '6',
    initials: 'LT',
    name: 'Lisa Thompson',
    email: 'lisa.t@email.com',
    status: 'active',
    role: 'Premium',
    balance: 5600,
    games: 203,
    winRate: 61,
    lastActive: '1 hour ago',
  },
  {
    id: '7',
    initials: 'JB',
    name: 'James Brown',
    email: 'james.brown@email.com',
    status: 'active',
    role: 'VIP',
    balance: 25800,
    games: 512,
    winRate: 74,
    lastActive: '5 min ago',
  },
  {
    id: '8',
    initials: 'AF',
    name: 'Amanda Foster',
    email: 'amanda.f@email.com',
    status: 'inactive',
    role: 'Player',
    balance: 200,
    games: 45,
    winRate: 42,
    lastActive: '2 weeks ago',
  },
]

// Mock Activity Log Data
export const mockActivityLog = [
  {
    id: '1',
    type: 'user_registered',
    title: 'New user David Kim registered',
    // description: 'Email verified, awaiting first deposit',
    timestamp: '2 minutes ago',
    icon: 'user-plus',
    color: 'text-emerald-400',
  },
  {
    id: '2',
    type: 'deposit',
    title: 'John Mitchell deposited 500 tokens',
    description: 'Payment via Visa •••• 4242',
    timestamp: '15 minutes ago',
    icon: 'dollar-sign',
    color: 'text-yellow-400',
  },
  {
    id: '3',
    type: 'tournament_win',
    title: 'Sarah Chen won Saturday Night Showdown',
    description: 'Prize: 2,500 tokens',
    timestamp: '1 hour ago',
    icon: 'trophy',
    color: 'text-yellow-400',
  },
  {
    id: '4',
    type: 'failed_login',
    title: 'Multiple failed login attempts for emily.r@email.com',
    description: '5 failed attempts from IP 192.168.1.45',
    timestamp: '2 hours ago',
    icon: 'alert-triangle',
    color: 'text-red-500',
    priority: 'high',
  },
  {
    id: '5',
    type: 'admin_login',
    title: 'Admin logged in from new device',
    description: 'Chrome on Windows, New York, USA',
    timestamp: '3 hours ago',
    icon: 'log-in',
    color: 'text-purple-400',
  },
  {
    id: '6',
    type: 'match_completed',
    title: 'Quick match completed between Player_45 and Player_99',
    description: 'Winner: Player_45, Stakes: 50 tokens',
    timestamp: '3 hours ago',
    icon: 'zap',
    color: 'text-gray-400',
  },
  {
    id: '7',
    type: 'withdrawal',
    title: 'James Brown requested withdrawal',
    description: 'Amount: 1,000 tokens to Bank ••••1234',
    timestamp: '4 hours ago',
    icon: 'send',
    color: 'text-yellow-400',
    status: 'pending-review',
  },
  {
    id: '8',
    type: 'profile_update',
    title: 'Lisa Thompson updated profile settings',
    description: 'Changed display name and avatar',
    timestamp: '5 hours ago',
    icon: 'settings',
    color: 'text-gray-400',
  },
]

// Mock Dashboard Stats
export const mockDashboardStats = [
  {
    title: 'Total Users',
    value: '2,847',
    change: '+124 this month',
    icon: 'users',
    color: 'bg-yellow-400/20 text-yellow-400',
  },
  {
    title: 'Total Revenue',
    value: '$48,290',
    change: '+12.5% from last month',
    icon: 'dollar-sign',
    color: 'bg-yellow-400/20 text-yellow-400',
  },
  {
    title: 'Active Games',
    value: '156',
    change: '23 tournaments running',
    icon: 'gamepad2',
    color: 'bg-yellow-400/20 text-yellow-400',
  },
  {
    title: 'Platform Growth',
    value: '+18.2%',
    change: 'vs. last quarter',
    icon: 'trending-up',
    color: 'bg-yellow-400/20 text-yellow-400',
  },
]

// Mock Tournaments
export const mockTournaments = [
  {
    id: '1',
    name: 'Saturday Night Showdown',
    image: '🏆',
    createdBy: 'Admin',
    createdAt: '2026-05-28',
    status: 'registering',
    entryFee: 50,
    prizePool: 1000,
    players: '0/16',
    startDate: '2026-05-30 at 20:00',
  },
]

// Mock Payouts Data
export const mockPayouts = [
  {
    title: 'Total Prize Pool',
    value: '$12,000',
    subtitle: 'Guaranteed + dynamic',
    icon: '🏆',
    color: 'border-yellow-400/30',
  },
  {
    title: 'Paid Out',
    value: '$7,500',
    subtitle: 'Smart contract verified',
    icon: '💲',
    color: 'border-emerald-400/30',
  },
  {
    title: 'Escrowed',
    value: '$4,500',
    subtitle: 'Smart contract verified',
    icon: '🔓',
    color: 'border-blue-400/30',
  },
  {
    title: 'Pending Reviews',
    value: '7',
    subtitle: '2 KYC, 3 fraud, 2 appeals',
    icon: '⌛',
    color: 'border-orange-400/30',
  },
  {
    title: 'Owed to Players',
    value: '$5,150',
    subtitle: '6 players awaiting payout',
    icon: '👤',
    color: 'border-red-400/30',
  },
]

// Mock Outstanding Payouts
export const mockOutstandingPayouts = [
  {
    player: 'QueenOfClubs',
    email: 'queen@example.com',
    tournament: 'Spring Championship',
    placement: '2nd',
    amount: '$2,500',
    method: 'Stripe Connect',
    owedSince: '2026-05-22',
    status: 'processing',
    blocker: '—',
  },
  {
    player: 'JokerWild',
    email: 'joker@example.com',
    tournament: 'Spring Championship',
    placement: '3rd',
    amount: '$1,000',
    method: 'USDC',
    owedSince: '2026-05-22',
    status: 'approved',
    blocker: 'Awaiting payout batch',
  },
  {
    player: 'DiamondKing',
    email: 'dking@example.com',
    tournament: 'Spring Championship',
    placement: '4th',
    amount: '$200',
    method: 'Zelle',
    owedSince: '2026-05-22',
    status: 'pending-review',
    blocker: 'Admin review',
  },
  {
    player: 'BluffMaster',
    email: 'bluff@example.com',
    tournament: 'Spring Championship',
    placement: '5th',
    amount: '$200',
    method: 'ACH',
    owedSince: '2026-05-22',
    status: 'kyc-needed',
    blocker: 'KYC incomplete',
  },
  {
    player: 'AceHigh',
    email: 'ace@example.com',
    tournament: 'Weekly Showdown',
    placement: '1st',
    amount: '$800',
    method: 'Stripe Connect',
    owedSince: '2026-05-25',
    status: 'pending',
    blocker: 'Tax form W9 missing',
  },
  {
    player: 'SpadeKing',
    email: 'spade@example.com',
    tournament: 'Pro League S2',
    placement: '3rd',
    amount: '$450',
    method: 'USDC',
    owedSince: '2026-05-26',
    status: 'pending',
    blocker: 'Wallet not verified',
  },
]

// Mock Rewards
export const mockRewards = [
  {
    id: '1',
    name: 'Starbucks - $20 Gift Card',
    company: 'Starbucks',
    category: 'Food',
    value: '$20',
    status: 'active',
    image: '☕',
  },
  {
    id: '2',
    name: "Ken's Koins",
    company: 'Love of Lockhart',
    category: 'Gaming',
    value: '100',
    status: 'active',
    image: '🎮',
  },
]

// Mock Merchandise
export const mockMerchandise = [
  {
    id: '1',
    name: 'iOS 16+ Phone Case',
    description: 'apple phone case',
    price: '$39.95',
    variants: '1 variant',
    status: 'active',
    image: '📱',
  },
]

// Mock Admin Users
export const mockAdminUsers = [
  {
    id: '1',
    userId: 'fe6622cb...',
    role: 'admin',
    permissions: [],
    assigned: 'Feb 4, 2026',
  },
  {
    id: '2',
    userId: '7f8cb8b5...',
    role: 'admin',
    permissions: ['manage users', 'manage tournaments', 'manage roles', '+3 more'],
    assigned: 'Feb 12, 2026',
  },
]

// Mock Settings
export const mockSettings = {
  company: 'Spades Gaming',
  adminEmail: 'admin@spades.com',
  timezone: 'America/New_York',
  notifications: {
    newUsers: true,
    securityAlerts: true,
    largeTransactions: true,
    dailySummary: false,
  },
  security: {
    twoFactorAuth: true,
    sessionTimeout: true,
    ipWhitelisting: false,
  },
}
